# Install the dependencies and run the application
name: CI Workflow

on:
    push:
    pull_request:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              run: |
                if ! command -v node &> /dev/null; then
                  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
                  sudo apt-get install -y nodejs
                else
                  echo "Node.js is already installed"
                fi

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install npm
              run: |
                if ! command -v npm &> /dev/null; then
                  sudo apt-get update
                  sudo apt-get install -y npm
                else
                  echo "npm is already installed"
                fi

            - name: Install npm dependencies
              run: |
                if [ ! -d "node_modules" ]; then
                  npm install
                else
                  echo "npm dependencies are already installed"
                fi

            - name: Install dotenv package
              run: |
                npm install dotenv

            - name: Run the application
              run: |
                export $(cat .env | xargs) # Load environment variables from .env
                node server.js &
                sleep 5
                curl -I http://localhost:$PORT # Use the PORT variable from .env