name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # QEMU is required for building multi-arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx is a Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract version from tag
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build, tag and push Docker images for different architectures
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          IMG=${IMG@L}

          docker buildx create --use --name multi-platform
          docker buildx inspect --bootstrap

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMG:${{steps.get_tag.outputs.VERSION}} \
            .
            
          docker push --all-tags $IMG

      - name: Update tag
        id: updated_tag
        run: |
          git fetch --all
          git checkout main

          IFS='.' read -r MAJOR MINOR PATCH <<< "${{steps.get_tag.outputs.VERSION}}"
          NEW_PATCH=$((PATCH + 1))
          echo "v$MAJOR.$MINOR.${NEW_PATCH}-pre" > VERSION

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add VERSION
          git commit -m "Bump version"
          git push origin HEAD:main
